# Site settings
title: Mouse on the Keys
header-img: img/home-bg.png
email: rjcolmed@gmail.com
copyright_name: rjcolmed
description: > # this means to ignore newlines until "baseurl:"
  Future, and It Works
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  rjcolmed
learn_profile: rjcolmed
email_username: rjcolmed@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
